const { promisePool } = require('../config/database');
const { generateRandomToken } = require('../utils/tokenUtils');
const { sendVerificationCode } = require('../utils/emailUtils');
const crypto = require('crypto');

// Send verification code to email
const sendEmailVerificationCode = async (req, res) => {
  console.log('📨 Send verification code request received');
  console.log('Request body:', req.body);
  
  try {
    const { email } = req.body;
    console.log('Processing email:', email);
    
    // Check if email already registered
    console.log('Checking if email exists...');
    const [existingUsers] = await promisePool.query(
      'SELECT id FROM users WHERE email = ?',
      [email]
    );
    console.log('Existing users found:', existingUsers.length);
    
    if (existingUsers.length > 0) {
      return res.status(409).json({
        status: 'error',
        message: 'Email already registered'
      });
    }
    
    // Generate 6-digit code
    const verificationCode = Math.floor(100000 + Math.random() * 900000).toString();
    const expiresAt = new Date(Date.now() + 10 * 60 * 1000); // 10 minutes
    
    // Format date for MySQL
    const expiresAtFormatted = expiresAt.toISOString().slice(0, 19).replace('T', ' ');
    console.log('Generated code:', verificationCode);
    console.log('Expires at:', expiresAtFormatted);
    
    // Delete any existing codes for this email
    console.log('Deleting old codes...');
    await promisePool.query(
      'DELETE FROM email_verification_codes WHERE email = ?',
      [email]
    );
    
    // Store code (id will be auto-generated by database)
    console.log('Inserting new code...');
    await promisePool.query(
      `INSERT INTO email_verification_codes (email, code, expires_at, attempts)
       VALUES (?, ?, ?, 0)`,
      [email, verificationCode, expiresAtFormatted]
    );
    console.log('Code stored in database');
    
    // Send email with code
    console.log('Sending email...');
    await sendVerificationCode(email, verificationCode);
    console.log('Email sent successfully');
    
    res.json({
      status: 'success',
      message: 'Verification code sent to your email',
      expiresIn: 600 // 10 minutes in seconds
    });
    
  } catch (error) {
    console.error('❌ Send verification code error:', error);
    console.error('Error details:', error.message);
    console.error('Stack:', error.stack);
    res.status(500).json({
      status: 'error',
      message: 'Failed to send verification code',
      details: process.env.NODE_ENV === 'development' ? error.message : undefined
    });
  }
};

// Verify email code
const verifyEmailCode = async (req, res) => {
  try {
    const { email, code } = req.body;
    
    const [codes] = await promisePool.query(
      'SELECT id, code, expires_at, attempts, verified FROM email_verification_codes WHERE email = ?',
      [email]
    );
    
    if (codes.length === 0) {
      return res.status(400).json({
        status: 'error',
        message: 'No verification code found. Please request a new code.'
      });
    }
    
    const codeData = codes[0];
    
    // Check if already verified
    if (codeData.verified) {
      return res.json({
        status: 'success',
        message: 'Email already verified'
      });
    }
    
    // Check expiration
    if (new Date(codeData.expires_at) < new Date()) {
      return res.status(400).json({
        status: 'error',
        message: 'Verification code expired. Please request a new code.'
      });
    }
    
    // Check attempts (max 5)
    if (codeData.attempts >= 5) {
      return res.status(400).json({
        status: 'error',
        message: 'Too many attempts. Please request a new code.'
      });
    }
    
    // Verify code
    if (codeData.code !== code) {
      // Increment attempts
      await promisePool.query(
        'UPDATE email_verification_codes SET attempts = attempts + 1 WHERE id = ?',
        [codeData.id]
      );
      
      return res.status(400).json({
        status: 'error',
        message: 'Invalid verification code',
        attemptsLeft: 5 - (codeData.attempts + 1)
      });
    }
    
    // Mark as verified
    await promisePool.query(
      'UPDATE email_verification_codes SET verified = TRUE WHERE id = ?',
      [codeData.id]
    );
    
    res.json({
      status: 'success',
      message: 'Email verified successfully'
    });
    
  } catch (error) {
    console.error('Verify code error:', error);
    res.status(500).json({
      status: 'error',
      message: 'Verification failed'
    });
  }
};

module.exports = {
  sendEmailVerificationCode,
  verifyEmailCode
};
